import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createFixtureBrowser} from './browser-fixture.mjs';

const {browser,context}=await createFixtureBrowser();
const page=await context.newPage();
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const events=()=>page.evaluate(()=>Object.values(window.__fixture.screeningEvents||{}));
try {
  await page.goto('http://127.0.0.1:4173');
  await page.locator('#homeView').waitFor({state:'visible'});
  await page.locator('button[data-route=screenings]').click();
  await page.locator('#screeningsView').waitFor({state:'visible'});
  const unrelated=await page.evaluate(()=>JSON.stringify([window.__fixture.draw,window.__fixture.movies,window.__fixture.availability]));
  await page.locator('#newScreening').click();
  await page.locator('#screeningQuery').fill('Drive');
  await page.locator('#screeningResults button').first().click();
  const date=await page.evaluate(()=>{const d=new Date(Date.now()+172800000);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+'T20:30'});
  await page.locator('#screeningDateTime').fill(date);
  await page.evaluate(()=>{window.__failNextUpdate=true});
  await page.locator('#saveScreening').click();
  await page.locator('#screeningFormError').filter({hasText:'Impossible'}).waitFor();
  assert.equal((await events()).length,0,'failed creation must not queue a message');
  assert.equal(await page.evaluate(()=>Object.keys(window.__fixture.screenings||{}).length),0);
  await page.locator('#saveScreening').click();
  await page.locator('#screeningForm').waitFor({state:'hidden'});
  let list=await events();assert.equal(list.length,1);assert.equal(list[0].type,'created');
  assert.equal(list[0].screening.movie.title,'Drive');assert.equal(list[0].actor,'ALEX');
  const first=list[0];
  await page.getByRole('button',{name:'Modifier la soirée Drive',exact:true}).click();
  await page.locator('#saveScreening').click();await page.locator('#screeningForm').waitFor({state:'hidden'});
  assert.equal((await events()).length,1,'unchanged save must stay silent');
  await page.getByRole('button',{name:'Modifier la soirée Drive',exact:true}).click();
  await page.locator('#screeningDateTime').fill(date.replace('20:30','21:00'));
  await page.evaluate(()=>{window.__failNextUpdate=true});
  await page.locator('#saveScreening').click();await page.locator('#screeningFormError').filter({hasText:'Impossible'}).waitFor();
  assert.equal((await events()).length,1,'failed edit must not queue a message');
  await page.locator('#saveScreening').click();await page.locator('#screeningForm').waitFor({state:'hidden'});
  list=await events();assert.equal(list.length,2);assert.equal(list[1].type,'updated');
  assert.equal(list[1].previous.startsAt,first.screening.startsAt);
  assert.equal(list[1].screening.startsAt-first.screening.startsAt,1800000);
  await page.getByRole('button',{name:'Annuler la soirée Drive',exact:true}).click();
  await page.evaluate(()=>{window.__failNextUpdate=true});await page.locator('#deleteHistoryConfirm').click();
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('Impossible d’annuler'));
  assert.equal((await events()).length,2,'failed deletion must not queue a message');
  assert.equal(await page.locator('#deleteHistoryModal').isVisible(),true);
  await page.locator('#deleteHistoryConfirm').click();await page.locator('#deleteHistoryModal').waitFor({state:'hidden'});
  list=await events();assert.equal(list.length,3);assert.equal(list[2].type,'deleted');
  assert.deepEqual(list[2].screening,list[1].screening,'cancelled film/date retained');
  assert.equal(await page.evaluate(()=>Object.keys(window.__fixture.screenings||{}).length),0);
  assert.equal(await page.evaluate(()=>JSON.stringify([window.__fixture.draw,window.__fixture.movies,window.__fixture.availability])),unrelated);
  const updates=await page.evaluate(()=>window.__updates.filter(update=>Object.keys(update).some(key=>key.startsWith('screeningEvents/'))));
  assert.equal(updates.length,3);
  for (const update of updates) assert.equal(Object.keys(update).filter(key=>key.startsWith('screenings/')).length,1,'each notification must share its atomic screening update');
  assert.deepEqual(errors,[]);
  fs.mkdirSync('tools/fixtures',{recursive:true});
  fs.writeFileSync('tools/fixtures/screening-events.json',JSON.stringify(await page.evaluate(()=>window.__fixture.screeningEvents),null,2)+'\n');
  console.log('PASS: browser create/edit/delete -> atomic notification queue; failures write neither event nor screening; unchanged edits silent; cancellation snapshot retained; draws unchanged.');
} finally { await browser.close(); }
