import assert from 'node:assert/strict';
import { createFixtureBrowser } from './browser-fixture.mjs';
const { browser, context } = await createFixtureBrowser({ reducedMotion: 'no-preference' });
let page = await context.newPage();
const errors = [];
const connect = p => p.on('pageerror', e => errors.push(e.message));
connect(page);
const shot = name => page.screenshot({path:`tools/screenshots/${name}.jpg`,type:'jpeg',quality:70,fullPage:true,animations:'allow'});
const ready = async () => {
  await page.goto('http://127.0.0.1:4173');
  await page.locator('#currentPickTitle').filter({hasText:'Initial D'}).waitFor();
  await page.locator('#heroPoster img').waitFor();
  await page.evaluate(() => document.fonts.ready);
};
try {
  await ready();
  await page.clock.install();
  await page.clock.pauseAt(new Date(Date.now()+1000));
  await page.locator('#heroNext').click();
  const before = await page.locator('#currentPickTitle').textContent();
  // Mouse focus and data refresh must not extend the 15-second interval.
  await page.locator('#currentPick').hover();
  await page.clock.fastForward(7000);
  await page.evaluate(() => window.__notify());
  await page.clock.fastForward(7999);
  assert.equal(await page.locator('#currentPickTitle').textContent(), before);
  await page.clock.fastForward(1);
  assert.notEqual(await page.locator('#currentPickTitle').textContent(), before);
  await page.locator('#heroPause').click();
  const paused = await page.locator('#currentPickTitle').textContent();
  await page.clock.fastForward(45000);
  assert.equal(await page.locator('#currentPickTitle').textContent(), paused);
  await page.locator('#heroPause').click();
  await page.clock.fastForward(15000);
  assert.notEqual(await page.locator('#currentPickTitle').textContent(), paused);
  await page.locator('#heroDetails').click();
  await page.locator('#ratingModal').waitFor({state:'visible'});
  const modalTitle = await page.locator('#currentPickTitle').textContent();
  await page.clock.fastForward(30000);
  assert.equal(await page.locator('#currentPickTitle').textContent(), modalTitle);
  await page.locator('#ratingModalClose').click();
  await page.clock.fastForward(15020);
  assert.notEqual(await page.locator('#currentPickTitle').textContent(), modalTitle);
  await page.clock.resume();
  await page.close();
  page = await context.newPage(); connect(page); await ready();
  await page.locator('#heroPause').click();
  await page.waitForTimeout(700);
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.locator('#currentPick').screenshot({path:'tools/screenshots/carousel-3d.jpg',type:'jpeg',quality:75});
  // Search states, duplicate indication, keyboard selection and one successful save.
  await page.locator('#movieQuery').fill('Initial');
  await page.locator('#results .movie').first().waitFor();
  assert.equal(await page.locator('#results .movie:disabled').count(), 1);
  await page.locator('#searchForm').scrollIntoViewIfNeeded();
  await page.waitForTimeout(500);
  await shot('search-desktop');
  for (const width of [390,320]) {
    await page.setViewportSize({width,height:844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await page.evaluate(() => document.querySelector('#results').getBoundingClientRect().bottom <= document.querySelector('#proposalPreview').getBoundingClientRect().top));
    await shot('search-'+width);
  }
  await page.locator('#movieQuery').press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.locator('#pendingMoviePanel').waitFor({state:'visible'});
  assert.equal(await page.locator('#pendingWarnings').getAttribute('open'), null);
  await page.locator('#pendingWarnings summary').click();
  await page.locator('#warningList button').first().click();
  await shot('proposal-mobile');
  await page.locator('#confirmMovieSelection').dblclick();
  await page.locator('#pendingMoviePanel').waitFor({state:'hidden'});
  const added = await page.evaluate(() => Object.values(window.__fixture.movies).filter(m => m.tmdbId===64690));
  assert.equal(added.length,1);
  assert.equal(added[0].triggerWarnings.length,1);
  assert.equal(added[0].backdropPath,'/backdrop.jpg');
  await page.locator('#movieQuery').fill('Initial');
  await page.locator('#results .movie').first().waitFor();
  assert.equal(await page.locator('#results .movie:disabled').count(),2);
  await page.locator('#clearMovieSearch').click();
  assert.equal(await page.locator('#results .movie').count(),0);
  await page.evaluate(() => {window.__searchFail=true});
  await page.locator('#movieQuery').fill('Erreur');
  await page.locator('.search-retry').waitFor();
  await page.evaluate(() => {window.__searchFail=false});
  await page.locator('.search-retry').click();
  await page.locator('#results .movie').first().waitFor();
  await page.locator('#clearMovieSearch').click();
  await page.setViewportSize({width:1440,height:1050});
  await page.locator('[data-route=draws]').click();
  await page.locator('#drawKeepSelectionToggle').click();
  await page.locator('#drawForcedMovie').selectOption('m2');
  const beforeTest = await page.evaluate(() => JSON.stringify(window.__fixture));
  const writes = await page.evaluate(() => window.__writes);
  await page.locator('#drawButton').click();
  await page.waitForFunction(() => document.querySelector('#drawStage').classList.contains('is-drawing'));
  await page.waitForTimeout(450);
  assert.equal(await page.locator('#coverStack').evaluate(el => getComputedStyle(el).transformStyle), 'preserve-3d');
  await page.locator('#drawStage').screenshot({path:'tools/screenshots/draw-orbit.jpg',type:'jpeg',quality:80});
  await page.waitForFunction(() => document.querySelector('#drawStage').classList.contains('is-impact'));
  await page.waitForTimeout(200);
  await page.locator('#drawStage').screenshot({path:'tools/screenshots/draw-reveal.jpg',type:'jpeg',quality:80});
  await page.waitForFunction(() => !document.querySelector('#drawButton').disabled);
  assert.equal(await page.locator('#winnerTitle').textContent(),'Interstellar');
  assert.equal(await page.evaluate(() => JSON.stringify(window.__fixture)),beforeTest);
  assert.equal(await page.evaluate(() => window.__writes),writes);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#drawButton').click();
  await page.waitForFunction(() => document.querySelector('#drawStage').classList.contains('is-drawing'));
  await page.waitForTimeout(400);
  await page.locator('#drawStage').screenshot({path:'tools/screenshots/draw-orbit-mobile.jpg',type:'jpeg',quality:75});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.waitForFunction(() => !document.querySelector('#drawButton').disabled);
  assert.equal(await page.evaluate(() => window.__writes),writes);
  await page.setViewportSize({width:1440,height:1050});
  await page.locator('button[data-route=home]').click();
  await page.locator('#homeView').waitFor({state:'visible'});
  assert.equal(await page.locator('#heroLabel').textContent(),'En sélection');
  assert.equal(await page.locator('.hero-navigation').isVisible(),true);
  // Old test records are excluded too, without deleting anyone's data.
  await page.evaluate(() => {
    window.__fixture.draw.current={title:'Ancien test',isTestDraw:true};
    window.__fixture.draw.history.oldTest={title:'Ancien test',isTestDraw:true,drawnAt:Date.now()};
    window.__notify();
  });
  await page.locator('[data-route=seen]').click();
  assert.ok(!(await page.locator('#seenList').innerText()).includes('Ancien test'));
  assert.deepEqual(errors,[]);
  console.log('PASS: 15s autoplay, refresh stability, pause/resume, modal; search mobile/keyboard/duplicates/retry/save; 3D orbit and reveal; simulation performs zero writes; legacy tests excluded.');
} catch(error) {
  await shot('motion-failure'); console.error(error); console.error(errors); process.exitCode=1;
} finally {await browser.close();}
